id: opecha:P000347
initial_creation_type: ocr
source_metadata:
  id: bdr:W23935
  title: མཁས་གྲུབ་ཆེན་པོ་བསོད་ནམས་བློ་གྲོས་ཀྱི་རྣམ་པར་ཐར་པ་མཐོང་བ་དོན་ལྡན་དད་པའི་གསལ་འདེབས་དང་གསང་བའི་རྣམ་ཐར་དང་མགུར་འབུམ
  volume: ''
  author: ''
