id: opecha:P000347
initial_creation_type: ocr
source_metadata:
  id: bdr:W23935
  title: མཁས་གྲུབ་ཆེན་པོ་བསོད་ནམས་བློ་གྲོས་ཀྱི་རྣམ་པར་ཐར་པ་མཐོང་བ་དོན་ལྡན་དད་པའི་གསལ་འདེབས་དང་གསང་བའི་རྣམ་ཐར་དང་མགུར་འབུམ
  volume:
    72853d48693d47e3ae6277b205fc9632:
      image_group_id: I3579
      title: ''
      volume_number: 1
      total_pages: 510
  author: ''
ebook_metadata:
  title: མཁས་གྲུབ་ཆེན་པོ་བསོད་ནམས་བློ་གྲོས་ཀྱི་རྣམ་པར་ཐར་པ་མཐོང་བ་དོན་ལྡན་དད་པའི་གསལ་འདེབས་དང་གསང་བའི་རྣམ་ཐར་དང་མགུར་འབུམ
  author: ''
  sku: P000347
  cover: cover.jpg
  layers:
  - pagination
