id: P000347
initial_creation_type: ocr
created_at: 14/03/2020
last_modified_at: 2021-12-16 15:35:13.459930
source_metadata:
  id: bdr:W23935
  title: མཁས་གྲུབ་ཆེན་པོ་བསོད་ནམས་བློ་གྲོས་ཀྱི་རྣམ་པར་ཐར་པ་མཐོང་བ་དོན་ལྡན་དད་པའི་གསལ་འདེབས་དང་གསང་བའི་རྣམ་ཐར་དང་མགུར་འབུམ
  author: ''
  volumes:
    72853d48693d47e3ae6277b205fc9632:
      image_group_id: I3579
      title: ''
      volume_number: 1
      total_pages: 510
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
